const APP_VERSION='3.3';
const BUDGET_PERIOD_DAYS=30;
const DEFAULT_CATEGORIES=[
  {id:'food',name:'Jedlo',icon:'🍔',limit:300,type:'spend',keywords:['lidl','tesco','kaufland','billa','fresh','coop','mcdonald','kfc','burger','restaurant','restauracia','pizza','obed','jedlo']},
  {id:'fuel',name:'Tankovanie',icon:'⛽',limit:90,type:'spend',keywords:['omv','shell','slovnaft','orlen','benzina']},
  {id:'gym',name:'Fitko',icon:'🏋️',limit:35,type:'toggle',keywords:['gym','fitness','fitko']},
  {id:'fun',name:'Zábava',icon:'🎮',limit:90,type:'spend',keywords:['steam','playstation','xbox','cinema','kino','bar','pub']},
  {id:'car',name:'Auto / rezerva',icon:'🚗',limit:80,type:'toggle',keywords:['autodiel','servis','pneuservis','car wash','umyvarka']},
  {id:'hygiene',name:'Hygiena / lekáreň',icon:'🧴',limit:45,type:'spend',keywords:['dm drogerie','101 drogerie','dr.max','benu','lekaren']},
  {id:'other',name:'Ostatné',icon:'🛍️',limit:30,type:'spend',keywords:[]}
];
const DEFAULT_STATE={
  settings:{budget:800,savings:150,workLunchPrice:6,periodStart:new Date(new Date().getFullYear(),new Date().getMonth(),1).getTime(),categories:DEFAULT_CATEGORIES},
  transactions:[],monthlyFlags:{},shopping:{},merchantRules:{},version:APP_VERSION
};
const RECIPES=[
  {n:'Kuracie prsia s ryžou a zeleninou',i:'🍗',c:3.6,k:650,p:52,ing:['200 g kuracích pŕs','90 g ryže','150 g mrazenej zeleniny','korenie + 1 ČL oleja'],s:['Ryžu uvar.','Kuracie nakrájaj, okoreň a opeč.','Pridaj zeleninu a podávaj s ryžou.']},
  {n:'Kuracie prsia s pečenými zemiakmi',i:'🥔',c:3.4,k:620,p:50,ing:['200 g kuracích pŕs','350 g zemiakov','100 g šalátu','jogurtový dip'],s:['Zemiaky nakrájaj a upeč.','Kuracie opeč na panvici.','Podávaj so šalátom a dipom.']},
  {n:'Morčacie cestoviny s paradajkou',i:'🍝',c:3.9,k:690,p:48,ing:['180 g morčacieho mäsa','100 g cestovín','150 g paradajkovej omáčky','20 g syra'],s:['Uvar cestoviny.','Mäso opeč a pridaj omáčku.','Zmiešaj a posyp syrom.']},
  {n:'Kuracie burrito bowl',i:'🌯',c:4.1,k:720,p:51,ing:['180 g kuracích pŕs','80 g ryže','80 g fazule','kukurica + salsa'],s:['Uvar ryžu.','Opeč kuracie s paprikou.','Daj do misky s fazuľou, kukuricou a salsou.']},
  {n:'Hovädzie s ryžou na ázijský spôsob',i:'🥩',c:5.2,k:700,p:46,ing:['180 g hovädzieho','90 g ryže','150 g zeleniny','sójová omáčka'],s:['Uvar ryžu.','Hovädzie prudko opeč.','Pridaj zeleninu a sójovú omáčku.']},
  {n:'Kuracie kari s ryžou',i:'🍛',c:4.0,k:710,p:49,ing:['190 g kuracích pŕs','90 g ryže','100 ml light kokosového mlieka','kari + zelenina'],s:['Uvar ryžu.','Opeč kuracie s kari.','Pridaj kokosové mlieko a zeleninu, krátko povar.']},
  {n:'Tuniakové cestoviny',i:'🐟',c:3.3,k:640,p:43,ing:['1 konzerva tuniaka','100 g cestovín','100 g paradajkovej omáčky','cibuľa'],s:['Uvar cestoviny.','Na panvici zohrej omáčku s tuniakom.','Zmiešaj s cestovinami.']},
  {n:'Kuracie stir-fry s ryžou',i:'🥢',c:3.8,k:660,p:50,ing:['190 g kuracích pŕs','85 g ryže','200 g wok zeleniny','sójová omáčka'],s:['Uvar ryžu.','Kuracie opeč vo woku.','Pridaj zeleninu a omáčku.']},
  {n:'Vajíčka, zemiaky a cottage',i:'🍳',c:2.8,k:600,p:38,ing:['3 vajcia','300 g zemiakov','150 g cottage','zelenina'],s:['Zemiaky uvar alebo upeč.','Priprav vajcia.','Podávaj s cottage a zeleninou.']},
  {n:'Kurací wrap s jogurtovým dresingom',i:'🌮',c:3.7,k:610,p:47,ing:['170 g kuracích pŕs','2 tortilly','zelenina','grécky jogurt'],s:['Kuracie opeč.','Tortilly naplň mäsom a zeleninou.','Pridaj jogurtový dresing.']},
  {n:'Kuracie rizoto',i:'🍚',c:3.5,k:650,p:46,ing:['180 g kuracích pŕs','90 g ryže','150 g hrášku a mrkvy','20 g parmezánu'],s:['Opeč kuracie.','Pridaj ryžu a zeleninu.','Dovar a na konci pridaj syr.']},
  {n:'Mleté morčacie so zemiakovou kašou',i:'🥘',c:4.1,k:700,p:48,ing:['200 g morčacieho mletého','350 g zemiakov','trocha mlieka','uhorka alebo šalát'],s:['Uvar zemiaky a sprav kašu.','Mleté mäso opeč s korením.','Podávaj so šalátom.']},
  {n:'Kuracie s kuskusom',i:'🥗',c:3.4,k:610,p:49,ing:['190 g kuracích pŕs','90 g kuskusu','paradajka + uhorka','citrón'],s:['Kuskus zalej horúcou vodou.','Kuracie opeč.','Zmiešaj zeleninu s kuskusom a pridaj mäso.']},
  {n:'Losos so zemiakmi',i:'🐟',c:5.8,k:680,p:42,ing:['160 g lososa','320 g zemiakov','brokolica','citrón'],s:['Lososa upeč alebo opeč.','Zemiaky uvar.','Pridaj brokolicu a citrón.']},
  {n:'Kuracie fajita s ryžou',i:'🌶️',c:3.9,k:680,p:50,ing:['190 g kuracích pŕs','85 g ryže','paprika + cibuľa','fajita korenie'],s:['Uvar ryžu.','Opeč kuracie s paprikou a cibuľou.','Ochut korením a podávaj.']},
  {n:'Hovädzí burger bowl',i:'🍔',c:5.0,k:720,p:45,ing:['180 g hovädzieho mletého','300 g zemiakov','šalát + paradajka','jogurtový burger dresing'],s:['Zemiaky upeč.','Mäso opeč ako placku alebo rozdrobené.','Daj do misky so zeleninou a dresingom.']},
  {n:'Kuracie pesto cestoviny',i:'🍝',c:4.2,k:730,p:50,ing:['180 g kuracích pŕs','100 g cestovín','20 g pesta','paradajky'],s:['Uvar cestoviny.','Kuracie opeč.','Zmiešaj s pestom a paradajkami.']},
  {n:'Tuniaková ryža s vajíčkom',i:'🍚',c:3.2,k:630,p:41,ing:['1 konzerva tuniaka','85 g ryže','2 vajcia','kukurica'],s:['Uvar ryžu a vajcia.','Pridaj tuniaka a kukuricu.','Premiešaj a dochuť.']},
  {n:'Kuracie s batatmi',i:'🍠',c:4.0,k:650,p:49,ing:['190 g kuracích pŕs','300 g batatov','zelené fazuľky','korenie'],s:['Bataty upeč.','Kuracie opeč.','Podávaj s fazuľkami.']},
  {n:'Morčacie chilli s ryžou',i:'🌶️',c:4.3,k:720,p:50,ing:['180 g morčacieho mletého','80 g ryže','100 g fazule','paradajky + chilli'],s:['Uvar ryžu.','Mäso opeč.','Pridaj fazuľu, paradajky a chilli, povar.']},
  {n:'Kuracie s gnocchi a špenátom',i:'🥬',c:4.4,k:710,p:47,ing:['180 g kuracích pŕs','250 g gnocchi','100 g špenátu','50 ml smotany light'],s:['Opeč kuracie.','Pridaj gnocchi a špenát.','Zjemni trochou smotany.']},
  {n:'Proteínová omeleta so šunkou',i:'🍳',c:3.0,k:560,p:44,ing:['3 vajcia','80 g kvalitnej šunky','30 g syra','zelenina + pečivo'],s:['Vajcia rozšľahaj.','Pridaj šunku a syr.','Opeč a podávaj so zeleninou.']},
  {n:'Kuracie teriyaki s ryžou',i:'🥢',c:4.0,k:690,p:49,ing:['190 g kuracích pŕs','90 g ryže','brokolica','teriyaki omáčka'],s:['Uvar ryžu.','Kuracie opeč.','Pridaj brokolicu a trochu teriyaki omáčky.']},
  {n:'Bravčová panenka so zemiakmi',i:'🥩',c:4.8,k:670,p:47,ing:['180 g bravčovej panenky','330 g zemiakov','šalát','horčicový dip'],s:['Zemiaky upeč.','Panenku opeč dohotova.','Podávaj so šalátom a dipom.']},
  {n:'Kurací šalát s pečenými zemiakmi',i:'🥗',c:3.7,k:590,p:48,ing:['180 g kuracích pŕs','250 g zemiakov','veľký šalát','jogurtový dressing'],s:['Zemiaky upeč.','Kuracie opeč.','Všetko spoj so šalátom a dressingom.']},
  {n:'Cestoviny bolognese fitness',i:'🍝',c:4.4,k:740,p:49,ing:['180 g chudého mletého mäsa','100 g cestovín','150 g paradajkovej omáčky','20 g parmezánu'],s:['Uvar cestoviny.','Mäso opeč a pridaj omáčku.','Podávaj s parmezánom.']},
  {n:'Kuracie s ryžovými rezancami',i:'🍜',c:4.0,k:660,p:47,ing:['180 g kuracích pŕs','100 g ryžových rezancov','wok zelenina','sójová omáčka'],s:['Rezance priprav podľa návodu.','Kuracie opeč so zeleninou.','Pridaj rezance a dochuť.']},
  {n:'Tortilla pizza s kuracím',i:'🍕',c:3.5,k:580,p:45,ing:['2 tortilly','150 g kuracích pŕs','80 g paradajkovej omáčky','60 g light mozzarelly'],s:['Tortilly potri omáčkou.','Pridaj kuracie a syr.','Zapeč 8–10 minút.']},
  {n:'Kuracie so šošovicou',i:'🥣',c:3.3,k:650,p:52,ing:['170 g kuracích pŕs','120 g uvarenej šošovice','zelenina','horčica + korenie'],s:['Kuracie opeč.','Šošovicu zohrej so zeleninou.','Spoj a dochuť.']},
  {n:'Hovädzie tacos',i:'🌮',c:4.9,k:700,p:44,ing:['170 g hovädzieho mletého','3 malé tortilly','šalát + paradajka','salsa'],s:['Mäso opeč s taco korením.','Napln tortilly.','Pridaj zeleninu a salsu.']},
  {n:'Kuracie s bulgurom a fetou',i:'🥗',c:3.9,k:640,p:49,ing:['180 g kuracích pŕs','90 g bulguru','30 g feta syra','paradajka + uhorka'],s:['Uvar bulgur.','Kuracie opeč.','Zmiešaj so zeleninou a fetou.']}
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=n=>new Intl.NumberFormat('sk-SK',{style:'currency',currency:'EUR'}).format(Number(n||0));
const parseNum=v=>Number(String(v??'').replace(',','.'))||0;
const monthKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`};
const clone=o=>JSON.parse(JSON.stringify(o));
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function migrate(raw){
  const r=raw&&typeof raw==='object'?raw:{}; const oldCats=r.settings?.categories||DEFAULT_CATEGORIES;
  const cats=DEFAULT_CATEGORIES.map(d=>({...d,...(oldCats.find(c=>c.id===d.id)||{}),keywords:d.keywords}));
  (oldCats||[]).filter(c=>!DEFAULT_CATEGORIES.some(d=>d.id===c.id)).forEach(c=>cats.push(c));
  return {settings:{budget:Number(r.settings?.budget??800)||800,savings:Number(r.settings?.savings??150)||0,workLunchPrice:Number(r.settings?.workLunchPrice??6)||6,periodStart:Number(r.settings?.periodStart)||new Date(new Date().getFullYear(),new Date().getMonth(),1).getTime(),categories:cats},transactions:Array.isArray(r.transactions)?r.transactions:[],monthlyFlags:r.monthlyFlags||{},shopping:r.shopping||{},merchantRules:r.merchantRules||{},version:APP_VERSION};
}
const store={get(){try{return migrate(JSON.parse(localStorage.getItem('money800')||'null'))}catch{return clone(DEFAULT_STATE)}},set(v){localStorage.setItem('money800',JSON.stringify(v))}};
let state=store.get(), recipeOffset=0, currentFilter='all', currentEditTxId=null;
function save(){store.set(state)} function cats(){return state.settings.categories} function cat(id){return cats().find(c=>c.id===id)||cats().at(-1)}
function periodStartTs(){return Number(state.settings.periodStart)||new Date(new Date().getFullYear(),new Date().getMonth(),1).getTime()}
function periodKey(){return `period-${new Date(periodStartTs()).toISOString().slice(0,10)}`}
function txPeriod(){return state.transactions.filter(t=>Number(t.ts)>=periodStartTs())}
function periodFlags(){if(!state.monthlyFlags[periodKey()])state.monthlyFlags[periodKey()]={};return state.monthlyFlags[periodKey()]}
function isPaid(id){return !!periodFlags()[id]}
function txSpent(id){return txPeriod().filter(t=>t.category===id).reduce((s,t)=>s+Number(t.amount||0),0)}
function catSpent(id){const c=cat(id),actual=txSpent(id);return c?.type==='toggle'&&isPaid(id)?Math.max(actual,Number(c.limit||0)):actual}
function totalSpent(){return cats().reduce((s,c)=>s+catSpent(c.id),0)}
function daysElapsed(){return Math.max(1,Math.floor((Date.now()-periodStartTs())/86400000)+1)} function daysLeft(){return Math.max(1,BUDGET_PERIOD_DAYS-daysElapsed()+1)}
function merchantKey(merchant=''){return String(merchant).toLowerCase().replace(/[^a-z0-9áäčďéíĺľňóôŕšťúýž ]/gi,' ').replace(/\s+/g,' ').trim()}
function autoCat(merchant=''){const m=merchant.toLowerCase(),rule=state.merchantRules?.[merchantKey(merchant)];if(rule&&cats().some(c=>c.id===rule))return rule;return cats().find(c=>(c.keywords||[]).some(k=>m.includes(k)))?.id||'other'}
function fingerprint(amount,merchant,text=''){return `${Number(amount).toFixed(2)}|${String(merchant).toLowerCase().replace(/\s+/g,' ').trim()}|${text.slice(0,80).toLowerCase().replace(/\s+/g,' ')}`}
function addTx(amount,merchant,category,source='manual',fp=''){const a=Number(amount);if(!a||!merchant)return false;const f=fp||fingerprint(a,merchant);if(state.transactions.some(t=>t.fingerprint&&t.fingerprint===f)){toast('Táto platba už je pridaná.');return false}state.transactions.push({id:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,amount:a,merchant,category:category||autoCat(merchant),source,ts:Date.now(),month:monthKey(),period:periodKey(),fingerprint:f});save();render();toast('Výdavok pridaný.');return true}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),1800)}
function navigate(name){$$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===name));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));window.scrollTo({top:0,behavior:'smooth'});if(name==='food')renderFood();if(name==='settings')renderSettings();if(name==='expenses')renderExpenses()}
function projection(){const elapsed=Math.max(1,Math.min(BUDGET_PERIOD_DAYS,daysElapsed())), variable=cats().filter(c=>c.type!=='toggle').reduce((s,c)=>s+txSpent(c.id),0), togglesPaid=cats().filter(c=>c.type==='toggle').reduce((s,c)=>s+catSpent(c.id),0), unpaidPlans=cats().filter(c=>c.type==='toggle'&&!isPaid(c.id)).reduce((s,c)=>s+Number(c.limit||0),0);return (variable/elapsed)*BUDGET_PERIOD_DAYS+togglesPaid+unpaidPlans}
function renderOverview(){
  const budget=state.settings.budget,spent=totalSpent(),remaining=budget-spent,free=budget-state.settings.savings-spent;
  $('#monthLabel').textContent=`Dnes ${new Intl.DateTimeFormat('sk-SK',{day:'numeric',month:'long',year:'numeric'}).format(new Date())}`;$('#periodLabel').textContent=`Obdobie od ${new Date(periodStartTs()).toLocaleDateString('sk-SK')} · ${daysLeft()} dní do plánovaného resetu`;
  $('#remainingAmount').textContent=fmt(remaining);$('#spentPill').textContent=`Minuté ${fmt(spent)}`;$('#txCountPill').textContent=`${txPeriod().length} platieb`;$('#budgetProgress').style.width=`${Math.min(100,Math.max(0,spent/Math.max(1,budget)*100))}%`;$('#dailyLimit').textContent=fmt(Math.max(0,free)/daysLeft());$('#savingsGoal').textContent=fmt(state.settings.savings);$('#freeAfterSavings').textContent=fmt(free);
  const proj=projection(), pct=Math.round(proj/Math.max(1,budget)*100);$('#forecastValue').textContent=fmt(proj);$('#forecastPct').textContent=`${pct}%`;$('#forecastRing').style.background=`conic-gradient(${pct>100?'var(--danger)':pct>90?'var(--warn)':'var(--accent)'} ${Math.min(360,pct*3.6)}deg,rgba(255,255,255,.08) 0deg)`;$('#forecastCopy').textContent=proj>budget?`Pri tomto tempe môžeš v tomto období prekročiť rozpočet asi o ${fmt(proj-budget)}.`:`Pri tomto tempe by ti na konci obdobia mohlo zostať približne ${fmt(budget-proj)}.`;
  $('#categoryList').innerHTML=cats().map(c=>categoryCard(c)).join('');bindToggleButtons();
  const r=getRecipe();$('#recipeActionText').textContent=`${r.n} · ~${fmt(r.c)}`;
}
function categoryCard(c){const sp=catSpent(c.id),lim=Number(c.limit||0),pct=lim?Math.min(100,sp/lim*100):0,paid=c.type==='toggle'&&isPaid(c.id),warn=pct>=100?'danger':pct>=75?'warn':'';let badge='V poriadku';if(pct>=100)badge='Limit vyčerpaný';else if(pct>=90)badge='Pozor: 90%+';else if(pct>=75)badge='Pozor: 75%+';if(c.type==='toggle')badge=paid?'🔴 Zaplatené':'⚪ Nezaplatené';return `<div class="category"><div class="category-top"><div class="category-left"><div class="cat-icon">${esc(c.icon)}</div><div><div class="category-name">${esc(c.name)}</div><div class="category-meta">${fmt(sp)} z ${fmt(lim)}</div></div></div><div class="category-right"><strong>${Math.round(pct)}%</strong><div class="remain">${fmt(Math.max(0,lim-sp))} ostáva</div></div></div><div class="bar"><div class="${warn}" style="width:${pct}%"></div></div><div class="category-footer"><span class="category-badge">${badge}</span>${c.type==='toggle'?`<button class="quick-btn ${paid?'paid':''}" data-paid="${c.id}">${paid?'Zrušiť':'Označiť zaplatené'}</button>`:''}</div></div>`}
function bindToggleButtons(){$$('[data-paid]').forEach(b=>b.onclick=()=>{periodFlags()[b.dataset.paid]=!isPaid(b.dataset.paid);save();render();toast(isPaid(b.dataset.paid)?'Označené ako zaplatené.':'Platba zrušená.')})}
function openEditTx(id){const t=state.transactions.find(x=>x.id===id);if(!t)return;currentEditTxId=id;$('#editTxAmount').value=String(t.amount).replace('.',',');$('#editTxMerchant').value=t.merchant;$('#editTxCategory').innerHTML=cats().map(c=>`<option value="${c.id}" ${c.id===t.category?'selected':''}>${esc(c.icon)} ${esc(c.name)}</option>`).join('');$('#editTxRemember').checked=false;$('#editTxSource').textContent=`Zdroj: ${t.source||'manual'} · ${new Date(t.ts).toLocaleString('sk-SK')}`;$('#editTxDialog').showModal()}
function renderExpenses(){const list=currentFilter==='all'?txPeriod():txPeriod().filter(t=>t.category===currentFilter);$('#txCategoryFilter').innerHTML=`<option value="all">Všetky kategórie</option>`+cats().map(c=>`<option value="${c.id}" ${currentFilter===c.id?'selected':''}>${esc(c.icon)} ${esc(c.name)}</option>`).join('');$('#expenseSummary').textContent=`Zobrazené: ${list.length} · spolu ${fmt(list.reduce((s,t)=>s+t.amount,0))} · ťukni na Upraviť pri platbe`;$('#emptyState').style.display=list.length?'none':'block';$('#transactions').innerHTML=list.sort((a,b)=>b.ts-a.ts).map(t=>{const c=cat(t.category);return `<div class="tx"><div class="tx-left"><div class="tx-icon">${esc(c.icon)}</div><div><div class="tx-title">${esc(t.merchant)}</div><div class="tx-sub">${esc(c.name)} · ${new Date(t.ts).toLocaleString('sk-SK',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})} · ${esc(t.source||'manual')}</div></div></div><div class="tx-right"><span class="tx-amt">−${fmt(t.amount)}</span><button class="edit-btn" data-edit-tx="${t.id}">Upraviť</button><button class="delete-btn" data-del="${t.id}">✕</button></div></div>`}).join('');$$('[data-edit-tx]').forEach(b=>b.onclick=()=>openEditTx(b.dataset.editTx));$$('[data-del]').forEach(b=>b.onclick=()=>{state.transactions=state.transactions.filter(t=>t.id!==b.dataset.del);save();render();toast('Výdavok vymazaný.')})}
function dayOfYear(){const n=new Date(),start=new Date(n.getFullYear(),0,0);return Math.floor((n-start)/86400000)}
function getRecipe(){let idx=(dayOfYear()+recipeOffset)%RECIPES.length;if(idx<0)idx+=RECIPES.length;return RECIPES[idx]}
function renderFood(){const fc=cat('food')||{limit:0},spent=catSpent('food'),remain=Math.max(0,Number(fc.limit||0)-spent),daily=remain/daysLeft(),r=getRecipe();$('#recipeDayLabel').textContent=`Dnešný tip · ${new Date().toLocaleDateString('sk-SK')}`;$('#foodRemaining').textContent=fmt(remain);$('#foodDaily').textContent=fmt(daily);$('#foodSpent').textContent=fmt(spent);$('#foodDailyBadge').textContent=`${fmt(daily)}/deň`;$('#recipeIcon').textContent=r.i;$('#recipeName').textContent=r.n;$('#recipeMacros').textContent=`~${fmt(r.c)} · ${r.k} kcal · ${r.p} g bielkovín`;$('#recipeIngredients').innerHTML=r.ing.map(x=>`<li>${esc(x)}</li>`).join('');$('#recipeSteps').innerHTML=r.s.map(x=>`<li>${esc(x)}</li>`).join('');const fit=$('#recipeFitBadge');fit.textContent=r.c<=daily||daily===0?'V dennom limite':'Nad dnešný limit';fit.className=`fit-badge ${r.c<=daily||daily===0?'good':'bad'}`;$('#workLunchBtn').textContent=`Pridať ${fmt(state.settings.workLunchPrice)}`;renderShopping(r)}
function shoppingKey(){return `${periodKey()}|${dayOfYear()+recipeOffset}`}
function renderShopping(r){const key=shoppingKey();if(!state.shopping[key])state.shopping[key]={};$('#shoppingList').innerHTML=r.ing.map((x,i)=>`<label class="shopping-item ${state.shopping[key][i]?'checked':''}"><input type="checkbox" data-shop="${i}" ${state.shopping[key][i]?'checked':''}><span>${esc(x)}</span></label>`).join('');$$('[data-shop]').forEach(ch=>ch.onchange=()=>{state.shopping[key][ch.dataset.shop]=ch.checked;save();renderShopping(r)})}
function parseAmount(txt){for(const p of [/(?:znizeny|znížený)\s+o\s+(-?\d{1,5}[\.,]\d{2})\s*(?:EUR|€)/i,/(-?\d{1,5}[\.,]\d{2})\s*(?:EUR|€)/i,/(?:EUR|€)\s*(-?\d{1,5}[\.,]\d{2})/i,/(-?\d{1,5})\s*(?:EUR|€)/i]){const m=txt.match(p);if(m)return Math.abs(Number(m[1].replace(',','.')))}return null}
function cleanMerchant(v=''){return String(v).trim().replace(/[.\s]+$/,'').replace(/\s+/g,' ')}
function parseMerchant(txt){const exact=txt.match(/Popis\s+transakcie\s*:\s*Platba\s+kartou[^,\n]*,\s*([^\n]+)/i);if(exact)return cleanMerchant(exact[1]);for(const p of [/obchodn(?:í|i)k(?:a|ovi)?\s*[:\-]?\s*([^\n,;]+)/i,/merchant\s*[:\-]?\s*([^\n,;]+)/i,/miesto\s*[:\-]?\s*([^\n,;]+)/i]){const m=txt.match(p);if(m)return cleanMerchant(m[1])}const lines=txt.split(/\n+/).map(s=>s.trim()).filter(Boolean);return cleanMerchant(lines.find(l=>!/eur|€|tatra|banka|platba|karta|debet|vazeny klient|vážený klient|zostatok|uctovny|aktualny|disponibilny/i.test(l))||'Neznámy obchod')}
function showParsed(txt,autoImport=false){const a=parseAmount(txt),m=parseMerchant(txt);if(!txt){$('#parseResult').textContent='Vlož text e-mailu.';return}if(!a){$('#parseResult').textContent='Suma sa nedala rozpoznať. Keď dostaneme skutočný B-mail, parser upravíme.';return}const c=autoCat(m),fp=fingerprint(a,m,txt),duplicate=state.transactions.some(t=>t.fingerprint===fp);$('#parseResult').innerHTML=`<div class="parse-preview"><b>${duplicate?'⚠️ Už pridané':'✅ Rozpoznané'}</b><br>${fmt(a)} · ${esc(m)} · ${esc(cat(c).name)}${duplicate?'':`<br><button id="importParsed" class="primary compact" style="margin-top:10px">Pridať platbu</button>`}</div>`;if(autoImport&&!duplicate){addTx(a,m,c,'Tatra B-mail test',fp);return}setTimeout(()=>{$('#importParsed')?.addEventListener('click',()=>addTx(a,m,c,'Tatra B-mail',fp))},0)}
function testEmail(){const samples=[`Vazeny klient,\n\n4.10.2026 15:12 bol zostatok Vasho uctu SKxxxxxxxxxxxxxxxxxxxx znizeny o 3,64 EUR.\nuctovny zostatok: 33,86 EUR\naktualny zostatok: 33,86 EUR\ndisponibilny zostatok: 33,86 EUR\n\nPopis transakcie: Platba kartou 4405**9260, NVIDIA CORPORATION.`, `Vazeny klient,\n\n4.10.2026 15:20 bol zostatok Vasho uctu SKxxxxxxxxxxxxxxxxxxxx znizeny o 18,47 EUR.\nuctovny zostatok: 100,00 EUR\n\nPopis transakcie: Platba kartou 4405**9260, LIDL SLOVENSKO.`, `Vazeny klient,\n\n4.10.2026 15:25 bol zostatok Vasho uctu SKxxxxxxxxxxxxxxxxxxxx znizeny o 40,00 EUR.\nuctovny zostatok: 60,00 EUR\n\nPopis transakcie: Platba kartou 4405**9260, OMV KOSICE.`];return samples[Math.floor(Math.random()*samples.length)]}

function handleShortcutImport(){
  const hash=location.hash||'';
  if(!hash.startsWith('#bmail='))return;
  let txt='';
  try{txt=decodeURIComponent(hash.slice(7))}catch{txt=hash.slice(7)}
  if(!txt)return;
  navigate('tatra');
  $('#emailText').value=txt;
  showParsed(txt,true);
  history.replaceState(null,'',location.pathname+location.search);
}

function renderSettings(){const b=state.settings;$('#budgetInput').value=String(b.budget).replace('.',',');$('#savingsInput').value=String(b.savings).replace('.',',');$('#workLunchInput').value=String(b.workLunchPrice).replace('.',',');$('#currentPeriodSummary').textContent=`Aktuálne obdobie začalo ${new Date(periodStartTs()).toLocaleDateString('sk-SK')} · minuté ${fmt(totalSpent())} · ${txPeriod().length} platieb`;renderCategoryEditor();updateBudgetSum()}
function renderCategoryEditor(){$('#categoryEditor').innerHTML=cats().map((c,idx)=>`<div class="cat-edit-card"><div class="cat-edit-head"><div class="cat-edit-title"><span>${esc(c.icon)}</span><span>${esc(c.name)}</span></div>${!DEFAULT_CATEGORIES.some(d=>d.id===c.id)?`<button class="mini-delete" data-delcat="${c.id}">Vymazať</button>`:''}</div><div class="cat-edit-grid"><label>Názov<input data-cat-name="${c.id}" value="${esc(c.name)}"></label><label>Limit (€)<input inputmode="decimal" data-cat-limit="${c.id}" value="${String(c.limit).replace('.',',')}"></label><label>Režim<select data-cat-type="${c.id}"><option value="spend" ${c.type==='spend'?'selected':''}>Bežné výdavky</option><option value="toggle" ${c.type==='toggle'?'selected':''}>Zaplatené / nezaplatené</option></select></label></div></div>`).join('');$$('[data-cat-limit]').forEach(i=>i.oninput=updateBudgetSum);$$('[data-delcat]').forEach(b=>b.onclick=()=>{state.settings.categories=state.settings.categories.filter(c=>c.id!==b.dataset.delcat);save();renderSettings();toast('Kategória vymazaná.')})}
function updateBudgetSum(){const sum=cats().reduce((s,c)=>s+parseNum(document.querySelector(`[data-cat-limit="${c.id}"]`)?.value??c.limit),0),budget=parseNum($('#budgetInput')?.value||state.settings.budget),el=$('#categoryBudgetSum');el.textContent=`Súčet limitov kategórií: ${fmt(sum)} z celkového rozpočtu ${fmt(budget)}.`;el.style.color=sum>budget?'var(--warn)':'var(--muted)'}
function render(){renderOverview();renderExpenses();renderFood();renderSettings()}
$$('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));$('#quickSettingsBtn').onclick=()=>navigate('settings');$('#overviewAddBtn').onclick=$('#expensesAddBtn').onclick=()=>$('#addDialog').showModal();
$('#merchantInput').oninput=e=>$('#categoryInput').value=autoCat(e.target.value);$('#saveTxBtn').onclick=e=>{e.preventDefault();const a=parseNum($('#amountInput').value),m=$('#merchantInput').value.trim();if(!a||!m)return;addTx(a,m,$('#categoryInput').value);$('#addForm').reset();$('#addDialog').close()};
$('#txCategoryFilter').onchange=e=>{currentFilter=e.target.value;renderExpenses()};$('#clearTxBtn').onclick=()=>{if(confirm('Vymazať všetky transakcie za všetky mesiace?')){state.transactions=[];save();render();toast('Transakcie vymazané.')}};
$('#editTxSave').onclick=e=>{e.preventDefault();const t=state.transactions.find(x=>x.id===currentEditTxId);if(!t)return;const amount=parseNum($('#editTxAmount').value),merchant=$('#editTxMerchant').value.trim(),category=$('#editTxCategory').value;if(!amount||!merchant)return;t.amount=amount;t.merchant=merchant;t.category=category;if($('#editTxRemember').checked)state.merchantRules[merchantKey(merchant)]=category;save();$('#editTxDialog').close();render();toast($('#editTxRemember').checked?'Transakcia opravená a pravidlo zapamätané.':'Transakcia opravená.')};
$('#editTxDelete').onclick=()=>{if(!currentEditTxId)return;if(confirm('Vymazať túto transakciu?')){state.transactions=state.transactions.filter(t=>t.id!==currentEditTxId);save();$('#editTxDialog').close();render();toast('Transakcia vymazaná.')}};
$('#prevRecipeBtn').onclick=()=>{recipeOffset--;renderFood()};$('#nextRecipeBtn').onclick=()=>{recipeOffset++;renderFood()};$('#addRecipeCostBtn').onclick=()=>{const r=getRecipe();addTx(r.c,r.n,'food','recept')};$('#workLunchBtn').onclick=()=>addTx(state.settings.workLunchPrice,'Obed v práci','food','rýchle pridanie');$('#resetShoppingBtn').onclick=()=>{state.shopping[shoppingKey()]={};save();renderFood()};
$('#makeTestEmailBtn').onclick=()=>{$('#emailText').value=testEmail();showParsed($('#emailText').value)};$('#testAndImportBtn').onclick=()=>{const t=testEmail();$('#emailText').value=t;showParsed(t,true)};$('#parseBtn').onclick=()=>showParsed($('#emailText').value.trim());
$('#saveMainSettingsBtn').onclick=()=>{state.settings.budget=parseNum($('#budgetInput').value)||800;state.settings.savings=parseNum($('#savingsInput').value);state.settings.workLunchPrice=parseNum($('#workLunchInput').value)||6;save();render();toast('Nastavenia uložené.')};$('#budgetInput').oninput=updateBudgetSum;
$('#saveCategoriesBtn').onclick=()=>{state.settings.categories=cats().map(c=>({...c,name:document.querySelector(`[data-cat-name="${c.id}"]`)?.value.trim()||c.name,limit:parseNum(document.querySelector(`[data-cat-limit="${c.id}"]`)?.value),type:document.querySelector(`[data-cat-type="${c.id}"]`)?.value||c.type}));save();render();toast('Limity kategórií uložené.')};
$('#addCategoryBtn').onclick=()=>$('#categoryDialog').showModal();$('#createCategoryBtn').onclick=e=>{e.preventDefault();const name=$('#newCatName').value.trim(),limit=parseNum($('#newCatLimit').value);if(!name||!limit)return;const id=`custom_${Date.now()}`;state.settings.categories.push({id,name,icon:$('#newCatIcon').value.trim()||'💳',limit,type:$('#newCatType').value,keywords:[]});save();$('#categoryForm').reset();$('#newCatIcon').value='💳';$('#categoryDialog').close();render();toast('Kategória pridaná.')};
$('#paydayResetBtn').onclick=()=>{if(confirm(`Prišla výplata? Týmto sa vynulujú aktuálne výdavky, zaplatené prepínače a nákupný zoznam. Nastavenia, kategórie a pravidlá obchodov zostanú.`)){state.transactions=[];state.monthlyFlags={};state.shopping={};state.settings.periodStart=Date.now();save();render();navigate('overview');toast('Nové rozpočtové obdobie začalo.')}};
$('#resetAppBtn').onclick=()=>{if(confirm('Naozaj vymazať nastavenia, transakcie a začať odznova?')){state=clone(DEFAULT_STATE);save();render();toast('Appka obnovená.')}};
function refreshSelects(){$('#categoryInput').innerHTML=cats().map(c=>`<option value="${c.id}">${esc(c.icon)} ${esc(c.name)}</option>`).join('')}
const oldRender=render;render=()=>{refreshSelects();oldRender()};
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js?v=8').then(r=>r.update()).catch(()=>{})}
render();navigate('overview');handleShortcutImport();
